### ISSUE TITLE
Lasagne version

### ISSUE THREAD

**Issue by skrish13** [PetarV-/X-CNN#1]
Hey!
Would you find it helpful if I were to implement the paper in lasagne as well? I guess you already know the advantages of lasagne over keras, and it's actually used by many people (who prefer more flexibility/ use of theano etc).

PS: Loved the paper :smile:

**Comment by PetarV-** [comment]
Hi, 

Thank you for your thoughts! We're glad you liked the paper :)

And of course, feel free to write a new implementation, as long as you refer properly to the original work (as by the terms of the MIT license). While I'm personally a larger proponent of Keras, there's absolutely no harm in having a reference implementation in another framework---and it might be helpful to others as well.

Cheers,
Petar & Duo

**Comment by skrish13** [comment]
I had implemented it back then. [Here](https://github.com/skrish13/X-CNN-Lasagne) it is, in case anyone is interested :)
